name: Generate TTS

on:
  workflow_dispatch:
  push:
    paths:
      - "_posts/**/*.md"

jobs:
  tts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-texttospeech python-frontmatter pydub

      - name: Authenticate with Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          echo "${GOOGLE_APPLICATION_CREDENTIALS_JSON}" > gcloud-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=gcloud-key.json

      - name: Generate TTS audio
        run: python scripts/generate_tts.py

      - name: Commit and push audio files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add assets/audio/*.mp3 || true
          git commit -m "Add TTS audio files" || echo "No changes to commit"
          git push
